color_space = 'RGB'  # Can be RGB, HSV, LUV, HLS, YUV, YCrCb, GRAY
orient = 30  # HOG orientations
pix_per_cell = 16  # HOG pixels per cell
cell_per_block = 2  # HOG cells per block
hog_channel = 'ALL'  # Can be 0, 1, 2, or "ALL"
spatial_size = (16, 16)  # Spatial binning dimensions
hist_bins = 16  # Number of histogram bins
spatial_feat = False  # Spatial features on or off
hist_feat = False  # Histogram features on or off
hog_feat = True  # HOG features on or off
y_start_stop = [400, 720]  # Min and max in y to search in slide_window()
x_start_stop = [0, 1280]  # ditto for x
pct_overlap = 0.7  # sliding window overlap percentage
heatmap_thresh = 33
num_frames = 30  # number of video frames over which to accumulate heatmap
min_ar, max_ar = 0.7, 3.0  # bounding box acceptable aspect ratio range
small_bbox_area, close_y_thresh = 80*80, 500
min_bbox_area = 40*40
use_pretrained = True  # load pre-trained SVM model from disk?
